# Generated by Django 2.2.1 on 2019-06-10 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20190609_2233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instruction',
            old_name='recipe',
            new_name='recipe_name',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='seasonality',
            field=models.CharField(default='AS', max_length=255),
        ),
        migrations.AddField(
            model_name='recipe',
            name='cuisine',
            field=models.CharField(default='world', max_length=50),
        ),
    ]
