# Generated by Django 2.2.1 on 2019-06-10 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20190610_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='seasonality',
            field=models.CharField(default='AS', max_length=30),
        ),
    ]
