# Generated by Django 2.2.1 on 2019-06-25 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20190625_0203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeitem',
            name='qty',
            field=models.IntegerField(default=0),
        ),
    ]
