# Generated by Django 2.2.1 on 2019-06-25 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20190625_0333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeitem',
            name='name',
        ),
    ]
