# Generated by Django 2.2.1 on 2019-06-10 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20190610_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='seasonality',
            field=models.CharField(choices=[('SP', 'Spring'), ('SU', 'Summer'), ('FA', 'Fall'), ('WI', 'Winter'), ('AS', 'All seasons')], default='AS', max_length=30),
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('ingredient_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='recipes.Ingredient')),
                ('qty', models.IntegerField()),
                ('unit', models.CharField(choices=[('CUP', 'Cups'), ('TSP', 'Teaspoons'), ('TBSP', 'Tablespoons'), ('PCS', 'Pieces'), ('LBS', 'Pounds'), ('NA', 'None')], default='NA', max_length=30)),
                ('recipe_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.Recipe')),
            ],
            bases=('recipes.ingredient',),
        ),
    ]
