# Generated by Django 2.2.1 on 2019-06-26 14:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_remove_recipeitem_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrecipe',
            name='meal_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
