# Generated by Django 2.2.1 on 2019-06-10 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_delete_recipeingredient'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('qty', models.IntegerField()),
                ('unit', models.CharField(choices=[('CUP', 'Cups'), ('TSP', 'Teaspoons'), ('TBSP', 'Tablespoons'), ('PCS', 'Pieces'), ('LBS', 'Pounds'), ('NA', 'None')], default='NA', max_length=30)),
                ('ingredient_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.Ingredient')),
                ('recipe_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.Recipe')),
            ],
        ),
    ]
