# Generated by Django 2.2.1 on 2019-07-06 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20190626_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeitem',
            name='unit',
            field=models.CharField(choices=[('TSP', 'Teaspoons'), ('TBSP', 'Tablespoons'), ('CUP', 'Cups'), ('PINT', 'Pint'), ('QRT', 'Quart'), ('GAL', 'Gallon'), ('OZ', 'Ounces'), ('LBS', 'Pounds'), ('G', 'Grams'), ('KG', 'Kilograms'), ('PCS', 'Pieces'), ('NA', 'None')], default='NA', max_length=30),
        ),
        migrations.AlterField(
            model_name='userrecipe',
            name='meal_time',
            field=models.CharField(choices=[('BR', 'Breakfast'), ('LU', 'Lunch'), ('DI', 'Dinner'), ('NA', 'Not specified')], default='NA', max_length=30),
        ),
    ]
