# Generated by Django 2.2.1 on 2019-07-06 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_auto_20190706_1417'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipeitem',
            options={'verbose_name': 'Recipe item'},
        ),
    ]
