# Generated by Django 2.2.1 on 2019-06-10 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_auto_20190610_0311'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipeitem',
            options={'verbose_name': 'Recipe Ingredient'},
        ),
    ]
