# Generated by Django 2.2.1 on 2019-07-07 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_auto_20190706_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeitem',
            name='qty',
            field=models.FloatField(default=0),
        ),
    ]
