# Generated by Django 2.2.1 on 2019-06-11 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_auto_20190610_0311'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipeitem',
            options={'verbose_name': 'Recipe Item'},
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients',
        ),
    ]
