# Generated by Django 2.2.1 on 2019-07-08 22:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_recipeitem_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ready_in',
            field=models.DurationField(default=datetime.timedelta(seconds=3600)),
        ),
        migrations.AddField(
            model_name='recipe',
            name='servings',
            field=models.IntegerField(default=1),
        ),
    ]
