# Generated by Django 2.2.1 on 2019-07-08 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_auto_20190708_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='cal',
            field=models.IntegerField(null=True),
        ),
    ]
