# Generated by Django 2.2.1 on 2019-06-15 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_recipe_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeitem',
            name='recipe_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recipes.Recipe'),
        ),
    ]
